### ISSUE TITLE
question about list-vlans & add-vlan functions

### ISSUE THREAD

**Issue by zkiroel** [viniarck/phpipam-pyclient#6]
hello, thanks for your phpipam-pyclient
try to add few functions like vrf/vlan adding
sooo
can't understand how to add vlans
example: if I take list-devices code-block 
and change device to vlan I got list-vlans - that work fine

but if I try to do the same and switch from add-device to add-vlan that did not work, can you help me with that or try to show me the way where I need to go?

thank you

**Comment by zkiroel** [comment]
dam, just done with it, my fall
line 158, have to use
`        return self._post(endpoint='vlan/', data=vlan).status_code`
instead of:
`        return self._post(endpoint='vlan/1/', data=vlan).status_code`

**Comment by viniarck** [comment]
Hi @thymikon, I'm glad you figured it out. If you need further help let me know.
